/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        pRegular: ["regular"],
      },
      spacing: {
        alexLeft: "398px",
        alexTop: "282px",
        seanLeft: "422px",
        seanTop: "232px",
        ibukiLeft: "446px",
        ibukiTop: "182px",
        necroLeft: "470px",
        necroTop: "132px",
        urienLeft: "494px",
        urienTop: "82px",
        akumaLeft: "518px",
        akumaTop: "32px",
        yangLeft: "456px",
        yangTop: "314px",
        twelveLeft: "480px",
        twelveTop: "264px",
        makotoLeft: "504px",
        makotoTop: "214px",
        chunLeft: "528px",
        chunTop: "164px",
        qLeft: "552px",
        qTop: "114px",
        remyLeft: "576px",
        remyTop: "64px",
        yunLeft: "598px",
        yunTop: "14px",
        kenLeft: "538px",
        kenTop: "296px",
        hugoLeft: "562px",
        hugoTop: "246px",
        elenaLeft: "586px",
        elenaTop: "196px",
        dudleyLeft: "610px",
        dudleyTop: "146px",
        oroLeft: "634px",
        oroTop: "96px",
        ryuLeft: "658px",
        ryuTop: "46px",
      },
    },
  },
  plugins: [],
};
