/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        pRegular: ["regular"],
        metropolis: ["Metropolis-Black"],
      },
      spacing: {
        alexLeft: "625px",
        alexTop: "355px",
        seanLeft: "655px",
        seanTop: "293px",
        ibukiLeft: "675px",
        ibukiTop: "232px",
        necroLeft: "697px",
        necroTop: "170px",
        urienLeft: "721px",
        urienTop: "107px",
        akumaLeft: "745px",
        akumaTop: "45px",
        yangLeft: "690px",
        yangTop: "395px",
        twelveLeft: "705px",
        twelveTop: "337px",
        makotoLeft: "731px",
        makotoTop: "270px",
        chunLeft: "755px",
        chunTop: "209px",
        qLeft: "785px",
        qTop: "145px",
        remyLeft: "805px",
        remyTop: "85px",
        yunLeft: "828px",
        yunTop: "22px",
        kenLeft: "772px",
        kenTop: "375px",
        hugoLeft: "789px",
        hugoTop: "310px",
        elenaLeft: "813px",
        elenaTop: "247px",
        dudleyLeft: "842px",
        dudleyTop: "185px",
        oroLeft: "861px",
        oroTop: "125px",
        ryuLeft: "890px",
        ryuTop: "63px",
      },
    },
  },
  plugins: [],
};
